version: 2
jobs:
  build:
    working_directory: /docker
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Instalando dependencias
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - run:
          name: Run tests
          command: |
            docker-compose up -d
            docker-compose run docker python test.py
      - deploy:
        name: Push aplicacion docker images
        command: |
          docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
          docker tag docker_docker $DOCKER_HUB_USER_ID/docker:$CIRCLE_SHA1
          docker tag docker_docker $DOCKER_HUB_USER_ID/docker:latest
          docker push $DOCKER_HUB_USER_ID/docker:$CIRCLE_SHA1
          docker push $DOCKER_HUB_USER_ID/docker:latest